name: C++ Unit Tests
concurrency:
  cancel-in-progress: true
  group: cpp-test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Configure CMake
        run: cmake -B build -S .
      - name: Build tests
        run: cmake --build build --config Release
      - name: Run unit tests
        run: ctest --test-dir build -C Release --output-on-failure